config/routes.rb
Rails.application.routes.draw do
  resources :checklists
  

            resources :users, only: [:new, :create]
            
            resources :user_sessions, only: [:create, :destroy]

            delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
            get '/sign_in', to: 'user_sessions#new', as: :sign_in
            

  root 'main#show', page: 'home'
          get '/main/:page' => 'pages#show'

end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	acts_as_authentic do |c|
    c.crypto_provider = Authlogic::CryptoProviders::Sha512
   end 
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	skip_before_action :verify_authenticity_token
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

private
	def current_user_session
	  return @current_user_session if defined?(@current_user_session)
	  @current_user_session = UserSession.find
	end

	def current_user
	  return @current_user if defined?(@current_user)
	  @current_user = current_user_session && current_user_session.user
	end

	helper_method :current_user_session, :current_user
end	

app/controllers/checklists_controller.rb
class ChecklistsController < ApplicationController
  skip_before_action :verify_authenticity_token
  wrap_parameters format: [:json, :xml, :url_encoded_form, :multipart_form]
  before_action :set_checklist, only: [:show, :edit, :update, :destroy]


  # GET /checklists
  # GET /checklists.json
  def index
    @checklists = Checklist.all
  end

  # GET /checklists/1
  # GET /checklists/1.json
  def show
  end

  # GET /checklists/new
  def new
    @checklist = Checklist.new
  end

  # GET /checklists/1/edit
  def edit
  end

  # POST /checklists
  # POST /checklists.json
  def create
    @checklist = Checklist.new(checklist_params)

    respond_to do |format|
      if @checklist.save
        format.html { redirect_to @checklist, notice: 'Checklist was successfully created.' }
        format.json { render :show, status: :created, location: @checklist }
      else
      
        format.html { render :new }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /checklists/1
  # PATCH/PUT /checklists/1.json
  def update
    respond_to do |format|
      if @checklist.update(checklist_params)
        format.html { redirect_to @checklist, notice: 'Checklist was successfully updated.' }
        format.json { render :show, status: :ok, location: @checklist }
      else
        format.html { render :edit }
        format.json { render json: @checklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /checklists/1
  # DELETE /checklists/1.json
  def destroy
    @checklist.destroy
    respond_to do |format|
      format.html { redirect_to checklists_url, notice: 'Checklist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_checklist
      @checklist = Checklist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def checklist_params
      params.require(:checklist).permit(:Client_Name, :Grounds, :Petitioner_Preg_Aff, :Pregnancy_Affidavit_Respondent, :Waiver_Petitioner_s, :Waiver_Respondent_s, :MSA, :Residency_Proof, :Social_Security_Petitioner, :Social_Security_Respondent, :A, :Discovery_Waiver_Signed_by_Both, :Discovery_Waiver_Signed_by_Petitioner, :Discovery_Waiver_Signed_by_Respondent, :Financial_Affidavit_Petitioner, :Financial_Affidavit_Respondent, :Child_Custody_Affidavit, :Parenting_Course_Husband, :Parenting_Course_Wife, :Parenting_Plan, :Gudelines, :Addendum, :Notes, :Client_Email_Address, :Send_Link_Email)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def show
    	render template: "main/#{params[:page]}"
    end
  end  

app/controllers/sessions_app_controller.rb
def current_user_session
	  return @current_user_session if defined?(@current_user_session)
	  @current_user_session = UserSession.find
	end

	def current_user
	  return @current_user if defined?(@current_user)
	  @current_user = current_user_session && current_user_session.user
	end

	helper_method :current_user_session, :current_user

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params)
    if @user_session.save
      flash[:success] = "Welcome back!"
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:success] = "Goodbye!"
    redirect_to root_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password, :remember_me)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(users_params)
    if @user.save
      flash[:success] = "Account registered!"
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def users_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checklists_helper.rb
module ChecklistsHelper
end

app/views/checklists/_form.html.erb
<%= form_for(@checklist) do |f| %>
  <% if @checklist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@checklist.errors.count, "error") %> prohibited this checklist from being saved:</h2>

      <ul>
      <% @checklist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Client_Name %><br>
    <%= f.text_field :Client_Name %>
  </div>
  <div class="field">
    <%= f.label :Grounds %><br>
    <%= f.text_field :Grounds %>
  </div>
  <div class="field">
    <%= f.label :Petitioner_Preg_Aff %><br>
    <%= f.text_field :Petitioner_Preg_Aff %>
  </div>
  <div class="field">
    <%= f.label :Pregnancy_Affidavit_Respondent %><br>
    <%= f.text_field :Pregnancy_Affidavit_Respondent %>
  </div>
  <div class="field">
    <%= f.label :Waiver_Petitioner_s %><br>
    <%= f.text_field :Waiver_Petitioner_s %>
  </div>
  <div class="field">
    <%= f.label :Waiver_Respondent_s %><br>
    <%= f.text_field :Waiver_Respondent_s %>
  </div>
  <div class="field">
    <%= f.label :MSA %><br>
    <%= f.text_field :MSA %>
  </div>
  <div class="field">
    <%= f.label :Residency_Proof %><br>
    <%= f.text_field :Residency_Proof %>
  </div>
  <div class="field">
    <%= f.label :Social_Security_Petitioner %><br>
    <%= f.text_field :Social_Security_Petitioner %>
  </div>
  <div class="field">
    <%= f.label :Social_Security_Respondent %><br>
    <%= f.text_field :Social_Security_Respondent %>
  </div>
  <div class="field">
    <%= f.label :A %><br>
    <%= f.text_field :A %>
  </div>
  <div class="field">
    <%= f.label :Discovery_Waiver_Signed_by_Both %><br>
    <%= f.text_field :Discovery_Waiver_Signed_by_Both %>
  </div>
  <div class="field">
    <%= f.label :Discovery_Waiver_Signed_by_Petitioner %><br>
    <%= f.text_field :Discovery_Waiver_Signed_by_Petitioner %>
  </div>
  <div class="field">
    <%= f.label :Discovery_Waiver_Signed_by_Respondent %><br>
    <%= f.text_field :Discovery_Waiver_Signed_by_Respondent %>
  </div>
  <div class="field">
    <%= f.label :Financial_Affidavit_Petitioner %><br>
    <%= f.text_field :Financial_Affidavit_Petitioner %>
  </div>
  <div class="field">
    <%= f.label :Financial_Affidavit_Respondent %><br>
    <%= f.text_field :Financial_Affidavit_Respondent %>
  </div>
  <div class="field">
    <%= f.label :Child_Custody_Affidavit %><br>
    <%= f.text_field :Child_Custody_Affidavit %>
  </div>
  <div class="field">
    <%= f.label :Parenting_Course_Husband %><br>
    <%= f.text_field :Parenting_Course_Husband %>
  </div>
  <div class="field">
    <%= f.label :Parenting_Course_Wife %><br>
    <%= f.text_field :Parenting_Course_Wife %>
  </div>
  <div class="field">
    <%= f.label :Parenting_Plan %><br>
    <%= f.text_field :Parenting_Plan %>
  </div>
  <div class="field">
    <%= f.label :Gudelines %><br>
    <%= f.text_field :Gudelines %>
  </div>
  <div class="field">
    <%= f.label :Addendum %><br>
    <%= f.text_field :Addendum %>
  </div>
  <div class="field">
    <%= f.label :Notes %><br>
    <%= f.text_field :Notes %>
  </div>
  <div class="field">
    <%= f.label :Client_Email_Address %><br>
    <%= f.text_field :Client_Email_Address %>
  </div>
  <div class="field">
    <%= f.label :Send_Link_Email %><br>
    <%= f.check_box :Send_Link_Email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/checklists/edit.html.erb
<h1>Editing Checklist</h1>

<%= render 'form' %>

<%= link_to 'Show', @checklist %> |
<%= link_to 'Back', checklists_path %>

app/views/checklists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Checklists</h1>

<table>
  <thead>
    <tr>
      <th>Client name</th>
      <th>Grounds</th>
      <th>Petitioner preg aff</th>
      <th>Pregnancy affidavit respondent</th>
      <th>Waiver petitioner s</th>
      <th>Waiver respondent s</th>
      <th>Msa</th>
      <th>Residency proof</th>
      <th>Social security petitioner</th>
      <th>Social security respondent</th>
      <th>A</th>
      <th>Discovery waiver signed by both</th>
      <th>Discovery waiver signed by petitioner</th>
      <th>Discovery waiver signed by respondent</th>
      <th>Financial affidavit petitioner</th>
      <th>Financial affidavit respondent</th>
      <th>Child custody affidavit</th>
      <th>Parenting course husband</th>
      <th>Parenting course wife</th>
      <th>Parenting plan</th>
      <th>Gudelines</th>
      <th>Addendum</th>
      <th>Notes</th>
      <th>Client email address</th>
      <th>Send link email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @checklists.each do |checklist| %>
      <tr>
        <td><%= checklist.Client_Name %></td>
        <td><%= checklist.Grounds %></td>
        <td><%= checklist.Petitioner_Preg_Aff %></td>
        <td><%= checklist.Pregnancy_Affidavit_Respondent %></td>
        <td><%= checklist.Waiver_Petitioner_s %></td>
        <td><%= checklist.Waiver_Respondent_s %></td>
        <td><%= checklist.MSA %></td>
        <td><%= checklist.Residency_Proof %></td>
        <td><%= checklist.Social_Security_Petitioner %></td>
        <td><%= checklist.Social_Security_Respondent %></td>
        <td><%= checklist.A %></td>
        <td><%= checklist.Discovery_Waiver_Signed_by_Both %></td>
        <td><%= checklist.Discovery_Waiver_Signed_by_Petitioner %></td>
        <td><%= checklist.Discovery_Waiver_Signed_by_Respondent %></td>
        <td><%= checklist.Financial_Affidavit_Petitioner %></td>
        <td><%= checklist.Financial_Affidavit_Respondent %></td>
        <td><%= checklist.Child_Custody_Affidavit %></td>
        <td><%= checklist.Parenting_Course_Husband %></td>
        <td><%= checklist.Parenting_Course_Wife %></td>
        <td><%= checklist.Parenting_Plan %></td>
        <td><%= checklist.Gudelines %></td>
        <td><%= checklist.Addendum %></td>
        <td><%= checklist.Notes %></td>
        <td><%= checklist.Client_Email_Address %></td>
        <td><%= checklist.Send_Link_Email %></td>
        <td><%= link_to 'Show', checklist %></td>
        <td><%= link_to 'Edit', edit_checklist_path(checklist) %></td>
        <td><%= link_to 'Destroy', checklist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Checklist', new_checklist_path %>

app/views/checklists/new.html.erb
<h1>New Checklist</h1>

<%= render 'form' %>

<%= link_to 'Back', checklists_path %>

app/views/checklists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client name:</strong>
  <%= @checklist.Client_Name %>
</p>

<p>
  <strong>Grounds:</strong>
  <%= @checklist.Grounds %>
</p>

<p>
  <strong>Petitioner preg aff:</strong>
  <%= @checklist.Petitioner_Preg_Aff %>
</p>

<p>
  <strong>Pregnancy affidavit respondent:</strong>
  <%= @checklist.Pregnancy_Affidavit_Respondent %>
</p>

<p>
  <strong>Waiver petitioner s:</strong>
  <%= @checklist.Waiver_Petitioner_s %>
</p>

<p>
  <strong>Waiver respondent s:</strong>
  <%= @checklist.Waiver_Respondent_s %>
</p>

<p>
  <strong>Msa:</strong>
  <%= @checklist.MSA %>
</p>

<p>
  <strong>Residency proof:</strong>
  <%= @checklist.Residency_Proof %>
</p>

<p>
  <strong>Social security petitioner:</strong>
  <%= @checklist.Social_Security_Petitioner %>
</p>

<p>
  <strong>Social security respondent:</strong>
  <%= @checklist.Social_Security_Respondent %>
</p>

<p>
  <strong>A:</strong>
  <%= @checklist.A %>
</p>

<p>
  <strong>Discovery waiver signed by both:</strong>
  <%= @checklist.Discovery_Waiver_Signed_by_Both %>
</p>

<p>
  <strong>Discovery waiver signed by petitioner:</strong>
  <%= @checklist.Discovery_Waiver_Signed_by_Petitioner %>
</p>

<p>
  <strong>Discovery waiver signed by respondent:</strong>
  <%= @checklist.Discovery_Waiver_Signed_by_Respondent %>
</p>

<p>
  <strong>Financial affidavit petitioner:</strong>
  <%= @checklist.Financial_Affidavit_Petitioner %>
</p>

<p>
  <strong>Financial affidavit respondent:</strong>
  <%= @checklist.Financial_Affidavit_Respondent %>
</p>

<p>
  <strong>Child custody affidavit:</strong>
  <%= @checklist.Child_Custody_Affidavit %>
</p>

<p>
  <strong>Parenting course husband:</strong>
  <%= @checklist.Parenting_Course_Husband %>
</p>

<p>
  <strong>Parenting course wife:</strong>
  <%= @checklist.Parenting_Course_Wife %>
</p>

<p>
  <strong>Parenting plan:</strong>
  <%= @checklist.Parenting_Plan %>
</p>

<p>
  <strong>Gudelines:</strong>
  <%= @checklist.Gudelines %>
</p>

<p>
  <strong>Addendum:</strong>
  <%= @checklist.Addendum %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @checklist.Notes %>
</p>

<p>
  <strong>Client email address:</strong>
  <%= @checklist.Client_Email_Address %>
</p>

<p>
  <strong>Send link email:</strong>
  <%= @checklist.Send_Link_Email %>
</p>

<%= link_to 'Edit', edit_checklist_path(@checklist) %> |
<%= link_to 'Back', checklists_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Florida Divorce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<h1>Florida Divorce!!</h1>

<div id='main-navbar'>
	<ul id='menu'>
		<li><%=link_to 'Checklists',checklists_path%></li>
	</ul>
</div>	




<%= yield %>

</body>
</html>

app/views/main/home.html.erb
<div style="width:80%;left:10%;position:absolute">

	<h1>Main Page</h1>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<h1>Sign In</h1></div>

<%= form_for @user_session do |f| %>
  <%= render 'shared/errors', object: @user_session %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :remember_me %>
    <%= f.check_box :remember_me %>
  </div>

  <%= f.submit "Log in!", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/users/new.html.erb
<div class="page-header"><h1>Register</h1></div>

<%= form_for @user do |f| %>
  <%= render 'shared/errors', object: @user %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
<% end %>